name: Docker Image CI

on:
  repository_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VM_VERSION: ${{ github.event.client_payload.version }}
      BASE64_FILE_CONTENTS: ${{ github.event.client_payload.base64_file_contents }}
    steps:
    - name: Extract client payload tarball
      if: ${{ github.event_name == 'repository_dispatch' }}
      run: |
        mkdir tmp && cd tmp
        echo $BASE64_FILE_CONTENTS > virtual-machine.tar.gz.base64
        base64 -d virtual-machine.tar.gz.base64 > virtual-machine.tar.gz
        tar xvfz virtual-machine.tar.gz
        ls -ltrSha
        ls -ltrSha debian-11.3-armhf-ci/

        
