name: Docker Image CI

on:
  repository_dispatch:
#   release:
#     types: [published]

jobs:
  release_vm:
    if: ${{ github.event_name == 'repository_dispatch' }}
    runs-on: ubuntu-latest
    env:
      VM_TAG: ${{ github.event.client_payload.tag }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Install dependencies
      run: go install github.com/github-release/github-release@v0.10.0
    - name: Validate that the artifact exists
      run: |
        ARTIFACT_FILENAME=`~/go/bin/github-release info \
          -u jamesmortensen \
          -r virtual-machine-releases \
          --tag $VM_TAG | grep artifact | awk '{print $3}' | sed 's/,$//g'`
        if [ "$ARTIFACT_FILENAME" == "$VM_TAG.tar.xz" ]; then
          echo "Artifact found...proceed to download..."
          echo "ARTIFACT_FILENAME=$ARTIFACT_FILENAME" >> $GITHUB_ENV
        else
          echo "Artifact not found...exiting..."
          ~/go/bin/github-release info \
            -u jamesmortensen \
            -r virtual-machine-releases \
            --tag $VM_TAG
          exit 1
        fi
    - name: Download and extract the artifact
      run: |
        curl \
          -L https://github.com/jamesmortensen/virtual-machine-releases/releases/download/$VM_TAG/$ARTIFACT_FILENAME \
          -o $ARTIFACT_FILENAME
        tar xvfJ $ARTIFACT_FILENAME
        ls -ltrSha
        
